server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:d:\Google Drive\T07_RECLIB\DataBase\recipes
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false

filesystem:
  images: d:\Google Drive\T07_RECLIB\DataBase\images\

